### ISSUE TITLE
Deleting meetups which haven't met in a while

### ISSUE THREAD

**Issue by Nirvikalpa108** [londontechmeetups/londontechmeetups.github.io#6]
Hi @JennyBrennan, this is a wonderful site! I noticed it hasn't been updated in a while. Let me know if you're interested in doing a bit of an update as I can help with this! One of the things I noticed is that a few of the meetups haven't met in a while, some since 2017, do you think these could be deleted? I would be happy to do this.

I found your site through the CFGirls website and I think it's really relevant, but let me know if you think it's not anymore or if there are other sites that you think already have up to date info!

Thank you so much!

**Comment by JennyBrennan** [comment]
Hi @Nirvikalpa108 - thanks so much for this! Sounds fantastic. 

I would love your help in removing old meetups/no longer active links! Anything that hasn't met since 2017 could be removed. 

As a result of this issue I've also made two changes:
- Updated the 'most recently updated' text on the website to reflect the truth, as we've had some additions this month!
- Added an instruction in the README to update this date when contributors make a PR, to make it obvious to viewers how fresh the list is

Thanks again!
